### PR TITLE
Login/Register Page

### PR DESCRIPTION
**Pull request by josiahandrew12**
I used bootstrap to create the Login/Register page. I added the picture below. Followed similar styling we did with the UI mockup.

Screen Shot 2022-04-02 at 8 52 49 PM
Screen Shot 2022-04-02 at 9 09 27 PM

### CODE REVIEW

**Comment by preethamcoder** [comment]
The login pages look great! There are some minor changes with the background styling, but that can be fixed later. We can change the aesthetics once this is integrated with the flask page.

**Comment by preethamcoder** [comment]
For the styling, are you going to use a separate CSS style file or do you want to embed it in the `<style>` tag in the HTML file? We can also define it tag-by-tag as you did here. Is there any requirement that mandates the use of CSS files?

**Comment by josiahandrew12** [comment]
No requirement, bootstrap was actually demonstrated and encouraged in class.

**Comment by josiahandrew12** [comment]
Since bootstrap is taking care of the heavy lifting I will continue doing it line by line no need for an extra css file.

**Pull request merged**
