### PR TITLE
Flask code

### PR DESCRIPTION
**Pull request by josiahandrew12**
Here is the code for Login/register db logic. The error return flask.jsonify "status"message is just a placeholder for now and plan to add more sophisticated way to show if a username is taken or password is wrong in next sprint.

### CODE REVIEW

**Comment by preethamcoder** [comment]
Line 45 on models.py, the db.create_all() is written twice. It will cause problems.

**Comment by preethamcoder** [comment]
Make sure to add a blank line on routes.py at line 78 to avoid any pylint errors.

**Comment by josiahandrew12** [comment]
> Make sure to add a blank line on routes.py at line 78 to avoid any pylint errors.
Sure

**Comment by preethamcoder** [comment]
> > Make sure to add a blank line on routes.py at line 78 to avoid any pylint errors.
> > Sure

Sounds good! We also need to do that in models.py, at line 45

**Comment by josiahandrew12** [comment]
> > > Make sure to add a blank line on routes.py at line 78 to avoid any pylint errors.
> > > Sure
> 
> Sounds good! We also need to do that in models.py, at line 45

Yeah running through some of the pylint errors now

**Comment by preethamcoder** [comment]
> > > > Make sure to add a blank line on routes.py at line 78 to avoid any pylint errors.
> > > > Sure
> > 
> > 
> > Sounds good! We also need to do that in models.py, at line 45
> 
> Yeah running through some of the pylint errors now

Hold on, I will lint them for you.

**Comment by josiahandrew12** [comment]
> > > > > Make sure to add a blank line on routes.py at line 78 to avoid any pylint errors.
> > > > > Sure
> > > 
> > > 
> > > Sounds good! We also need to do that in models.py, at line 45
> > 
> > 
> > Yeah running through some of the pylint errors now
> 
> Hold on, I will lint them for you.

Alright cool.

**Comment by preethamcoder** [comment]
Got 10/10 linting score. pushing changes right now

**Review by TracyMichaels — APPROVED** [review]
looks good

**Comment by preethamcoder** [comment]
Alright, forget it, we will need to lint the files later any way

**Pull request merged**
